apiVersion: v1
kind: Service
metadata:
  name: inspect-service
  namespace: personal
spec:
  type: ClusterIP
  selector:
    app: inspect
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
